apiVersion: v1
kind: Secret
metadata:
  name: grow-user-secret
type: Opaque
stringData:
  PORT: "3001"

  DB_HOST: "34.50.60.106"
  DB_USER: "user_service"
  DB_PASSWORD: "@Wjdkrdnjs47"
  DB_NAME: "user_db"

  RABBITMQ_URL: "amqp://guest:guest@34.50.25.118:5672"

  JWT_ACCESS_SECRET: "cloud_computing_2026_grow_access_secret_key"
  JWT_REFRESH_SECRET: "cloud_computing_2026_grow_refresh_secret_key"
  ACCESS_TOKEN_EXPIRES_IN: "1h"
  REFRESH_TOKEN_EXPIRES_IN: "30d"

  USER_EVENT_EXCHANGE: "user.events"

  MISSION_SERVICE_URL: "http://mission:3003"
  GROWTH_SERVICE_URL: "http://growth-diary:3005"
  ACHIEVEMENT_SERVICE_URL: "http://achievement:3002"