apiVersion: apps/v1
kind: Deployment
metadata:
  name: grow-user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grow-user
  template:
    metadata:
      labels:
        app: grow-user
    spec:
      containers:
        - name: grow-user
          image: jjwon0407/grow-user:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          envFrom:
            - secretRef:
                name: grow-user-secret
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  type: LoadBalancer
  selector:
    app: grow-user
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grow-user-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grow-user-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
